apiVersion: v1
kind: ConfigMap
metadata:    
  labels:
    app: nifi
    app.kubernetes.io/managed-by: Kubefi    
    heritage: Kubefi    
  name: {{ name }}-config
data:
  {{ get_files "configs" 4}}
