apiVersion: v1
kind: ConfigMap
metadata:    
  labels:
    app: nifi
    app.kubernetes.io/managed-by: Kubefi    
    heritage: Kubefi    
  name: {{ name }}-config
data:
  authorizers-empty.xml: |+
    {{ authorizers-empty.xml }}
