{{# if ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ ingress.ingressClass }}
  labels:
    app: nifi
    app.kubernetes.io/managed-by: Kubefi
    heritage: Kubefi
  name: {{ name }}-ingress
spec:
  rules:
  - host: {{ ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ name }}
          servicePort: 80
        path: /
{{/if}}