apiVersion: v1
kind: Service
metadata:  
  labels:
    app: nifi
    app.kubernetes.io/managed-by: Kubefi
    release: nifi
  name: {{ name }}
spec:  
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nifi
    release: nifi
  sessionAffinity: None
  type: ClusterIP