apiVersion: v1
kind: Service
metadata:
  labels:
    app: nifi
    app.kubernetes.io/managed-by: Kubefi
    heritage: Kubefi
    release: nifi
  name: {{ name }}-headless
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: cluster
      port: 6007
      protocol: TCP
      targetPort: 6007
  selector:
    app: nifi
    release: nifi
  sessionAffinity: None
  type: ClusterIP