apiVersion: io.github.novakov-alexey/v1
kind: NiFiDeployment
metadata:
  name: my-nifi
spec:
  image: apache/nifi:1.11.4
  nifiReplicas: 2
  zk:
    replicas: 2
    image: zookeeper:3.5.5
  loggingConfigMap: custom-logback-config
  ingress:
    host: 51.116.130.46.xip.io
    ingressClass: nginx
  nifiResources:
    jvmHeapSize: 2g
    requests:
      cpu: 200m
      memory: 1024Mi