apiVersion: io.github.novakov-alexey/v1
kind: NiFiDeployment
metadata:
  name: my-nifi
spec:
  image: apache/nifi:1.11.4
  nifiReplicas: 3
  zk:
    replicas: 3
    image: zookeeper:3.5.5
  loggingConfigMap: custom-logback-config
  nifiResources:
    jvmHeapSize: 2g
    requests:
      cpu: 2000m
      memory: 2048Mi