apiVersion: io.github.novakov-alexey/v1
kind: NiFiDeployment
metadata:
  name: my-nifi
spec:
  image: apache/nifi:1.11.4
  nifiReplicas: 1
  ldap:
    host: ldap://ldap-service:389
  zk:
    replicas: 1
    image: zookeeper:3.5.5
  loggingConfigMap: custom-logback-config
  nifiResources:
    jvmHeapSize: 1g
    requests:
      cpu: 200m
      memory: 1Gi