apiVersion: v1
kind: Service
metadata:
  labels:
    app: ldap
  name: ldap-service
spec:
  ports:
    - name: openldap
      port: 389
    - name: openldaps      
      port: 636
  selector:
    app: ldap
